apiVersion: apps/v1
kind: Deployment
metadata:
  name: vmmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vmmanager
  template:
    metadata:
      labels:
        app: vmmanager
    spec:
      containers:
      - name: vmmanager
        image: testacr1984.azurecr.io/vmmanager:v1
        ports:
        - containerPort: 8010
---

apiVersion: v1
kind: Service
metadata:
  name: vmmanager
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8010
  selector:
    app: vmmanager
